---
# Install and configure application code

- name: install supervisor
  apt: name=supervisor state=present

- name: install pip
  apt: name=python-pip state=present

- name: install virtualenv
  apt: name=python-virtualenv state=present

- name: install gunicorn
  pip: name=gunicorn

- name: install guacamole
  pip: name='https://github.com/Antojitos/guacamole/archive/{{ guacamole_version }}.tar.gz'

- name: create guacamoles config directory
  file: path=/etc/guacamole state=directory mode=0755

- name: create guacamoles data directory
  file: path={{ guacamole_base_dir }} state=directory mode=0755

- name: create guacamoles files directory
  file: path={{ guacamole_base_dir }}/files state=directory mode=0755

- name: create configuration file for guacamole
  template: src=guacamole-config.py.j2 dest=/etc/guacamole/config.py

- name: create configuration file for supervisor
  template: src=supervisor-guacamole.conf.j2 dest=/etc/supervisor/conf.d/guacamole.conf
  notify: reload supervisor
